Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /(?:(?!.+_spec.rb).)*$/
Style/ClassVars:
  Exclude:
    - !ruby/regexp /(?:(?!.+_resolver.rb).)*$/
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'spec/mocks/**/*'
