sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby-head
cache:
  bundler: true
before_install:
  - gem update --system
  - gem install bundler
  - bundle install

script:
#  - bundle exec rubocop
#  - bundle exec rubycritic --no-browser -s 80 -f console
  - bundle exec rake spec