sudo: false
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - jruby-9.2.7.0
cache:
  bundler: true
before_install:
  - gem update --system
  - gem install bundler
  - sudo apt-get -y install libgmp-dev
  - sudo apt-get install ruby-dev
  - gem install psych -v '3.1.0' --source 'https://rubygems.org/'

addons:
  sonarcloud:
    organization: "puppet"
    token:
      secure: "775bbcca7b9ed3903ba8beddbb961eb13d885e2d" # encrypted value of your token
script:
#  - bundle exec rubocop
#  - bundle exec rubycritic --no-browser -s 80 -f console
  - bundle exec rake spec
  - sonar-scanner