# frozen_string_literal: true

describe 'NetworkingDomain' do
  before do
    allow(Open3).to receive(:capture2)
      .with('cat /etc/resolv.conf')
      .and_return("# Generated by NetworkManager\nsearch example.puppetlabs.net\nnameserver 8.8.8.8\n")
  end
  it 'returns networking Domain' do
    expect(Facter::Resolvers::NetworkingDomain.resolve(:networking_domain)).to eq('example.puppetlabs.net')
  end
end
