---
name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rubocop_checks:
    runs-on: ubuntu-18.04
    name: RuboCop
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Rubocop checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install --jobs 3 --retry 3
      - run: bundle exec rubocop --parallel

  rtc:
    runs-on: ubuntu-latest
    name: RuboCop TODO
    steps:
      - uses: actions/checkout@v1
      - uses: gimmyxd/rtc-action@0.0.5

  commit_checks:
    runs-on: ubuntu-18.04
    name: commit message
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Commit message checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install --jobs 3 --retry 3
      - run: bundle exec rake commits
