---
name: GitHub hosted facter CI

on:
  push:
    branches:
      - FACT-2569

jobs:
  ci:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    env:
      BP_ROOT: beaker-puppet
      FACTER_4_ROOT: facter_4

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          path: facter_4

      - name: Clone facter 3 repo
        uses: actions/checkout@v2
        with:
          repository: puppetlabs/facter
          ref: master
          path: facter_3

      - name: Clone beaker-puppet repo
        uses: actions/checkout@v2
        with:
          repository: puppetlabs/beaker-puppet
          ref: master
          path: beaker-puppet

      - name: Install Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Set agent latest SHA
        run: echo ::set-env name=SHA::`curl --fail --silent GET --url http://builds.delivery.puppetlabs.net/passing-agent-SHAs/puppet-agent-master`

      - name: SHA value
        run: echo $SHA

      - name: Run presuite
        run: bash facter_4/.github/actions/presuite.sh

      - name: Run acceptance tests
        run: cd facter_3/acceptance && beaker exec tests
