---
name: GitHub hosted facter CI

on: [push]

jobs:
  ci:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    env:
      FACTER_3_ROOT: facter_3
      FACTER_4_ROOT: facter_4
      SHA: latest
      BEAKER_VERSION: git://github.com/mihaibuzgau/beaker#master

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          path: facter_4

      - name: Clone facter 3 repo
        uses: actions/checkout@v2
        with:
          repository: puppetlabs/facter
          ref: master
          path: facter_3

      - name: Install Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Run acceptance tests
        run: |
          sudo gem install bundler &
          sudo cd $FACTER_3_ROOT/acceptance && bundle install &
          sudo BP_ROOT=`bundle info beaker-puppet --path` &
          sudo bundle exec beaker init -h ubuntu1804-64a{hypervisor=none\,hostname=localhost} -o config/aio/options.rb &
          sudo bundle exec beaker provision &
          sudo bundle exec beaker exec pre-suite --pre-suite $BP_ROOT/setup/aio/010_Install_Puppet_Agent.rb &
          sudo bundle exec beaker exec tests


