---
name: GitHub hosted facter CI

on:
  push:
    branches:
      - FACT-2569

jobs:
  ci:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    env:
      BP_ROOT: "${GITHUB_WORKSPACE}/beaker-puppet"

    steps:
#      - name: Checkout current PR
#        uses: actions/checkout@v2
#        with:
#          path: facter_4
#
#      - name: Clone facter 3 repo
#        uses: actions/checkout@v2
#        with:
#          repository: puppetlabs/facter
#          ref: master
#          path: facter_3

#      - name: Clone beaker-puppet repo
#        uses: actions/checkout@v2
#        with:
#          repository: puppetlabs/beaker-puppet
#          ref: master
#          path: beaker-puppet

#      - name: Install Ruby 2.6
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '2.6'
#
#      - name: Install beaker
#        run: gem install beaker

      - name: beaker path
        run: echo $BP_ROOT
