---
name: GitHub hosted facter CI

on:
  push:
    branches:
      - FACT-2569

jobs:
  ci:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    env:
      FACTER_3_ROOT: facter_3
      FACTER_4_ROOT: facter_4
      BEAKER_ROOT: beaker
      SHA: latest

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          path: facter_4

      - name: Clone facter 3 repo
        uses: actions/checkout@v2
        with:
          repository: puppetlabs/facter
          ref: master
          path: facter_3

      - name: Clone Mihai's beaker fork
          uses: actions/checkout@v2
          with:
            repository: mihaibuzgau/beaker
            ref: master
            path: beaker

      - name: Install Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'

      - name: Run acceptance tests
        run: sudo -E bash -c facter_4/.github/actions/presuite.sh
