---
name: Unit tests

on: [pull_request]

jobs:
  unit_tests:
    name: Ruby version
    strategy:
      matrix:
        ruby: [ 2.3, 2.4, 2.5, 2.6, 2.7, jruby ]
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Rspec checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle update
      - run: bundle exec rake spec

  rspec_checks:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Rubocop checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install bundler
      - run: bundle update
      - run: bundle exec rubocop
