---
name: Facter 4 unit test

on: [pull_request, push]

jobs:
  unit_tests:
    name: Run unit tests on Ruby
    strategy:
      matrix:
        ruby: [ 2.3, 2.4, 2.5, 2.6, 2.7, jruby ]
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Rubocop & rspec checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle update
      - run: bundle exec rubocop
      - run: bundle exec rake spec