---
name: Unit tests

on: [pull_request]

jobs:
  linux_unit_tests:
    name: Ruby version
    strategy:
      matrix:
        ruby: [ 2.3, 2.7, jruby ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Rspec checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: bundle install --jobs 3 --retry 3
      - run: bundle exec rake spec

  windows_unit_tests:
    runs-on: windows-2019
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Rspec checks
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install bundler
      - run: bundle install --jobs 3 --retry 3
      - run: bundle exec rake spec

      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
