---
name: Facter 4 unit test

on: [pull_request, push]

jobs:
  unit_tests:
    name: Run unit tests
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Rubocop checks
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: bundle exec rubocop
      - run: bundle exec rake spec

